language: minimal
cache:
  directories:
    - $HOME/.jabba/

matrix:
  include:
    - name: "Linux JDK8"
      os: linux
      dist: xenial
      env:
        - JDK="adopt@1.8"
    - name: "Linux JDK11"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.11"
    - name: "Linux JDK13"
      os: linux
      dist: xenial
      env:
        - JDK="openjdk@1.13"

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis" 
    
before_install:
  # Check out the script set
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - cd $WD

script: 
  - ant test

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../plugin-Cast3m.zip *; cd ..
  - ant install
  - zip -r Funz-Cast3m.zip Funz-Cast3m
  
deploy:
  provider: releases
  api_key:
    secure: kiIqGxYORjao7hXW2Ba6NXviosUWSBdulJH4WQPXWUJe4eUJakWsalqIZR3jfV0WALl1UFFhUwSWU79bs2VT+E42FJEBxRjkIgegT+fXST7yYrE3krrPAS8eTP2JGPe7oEO7Uco0zLROnTJ8lOvg6RkMePGVXjGUUtWuvPfowTTYW17jcDnxRfhncgM4wVafkmgPvKTSvySLu+vjWYczs1Hd4PogKyz+9FmvI2SZg5oZcWeEdv0vYUislwuU7sONKSN14gpJ3hqA9BNFmMUKRKfnPYi5oRulOPKlZrqdj+m8dtPTYSIKd22igOVtgEsn4fn6Sqzprs0AxgGyL5vuEPJZiIJpQTDaqqOxDsFiE4gsWeajBO06esLkfHiQ+tvd0QjmE6OyxH5y0HnRw8q8FNhZmG8/xNIe/1F+CXBCn6HKATn7W97sUMypL//W0FpjpCgSWfXUMUC7byMtk02vT0b6UioFpe8o8fN9hxEflD/voZDwzrLFNi/989+H9mwQfJ1n/dfbmp3Rsl1v4TxLrWV1BTTWLVSNlOK/d+eTc5GotOhfrD0KVvOeQu+VU57QLO20oAjWIeajA4cOmbT54I6mdr1XV+No52CG/g9SmnNGt6qKuRxsZ2naf3rfF9Girq8v8OEttk6S/d7Cv/1emfVYKhpwXzWGlgDWyG84wfY=
  file_glob: true
  file:
    - Funz-*.zip
    - plugin-*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
